package main

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/aphexddb/omarket/client"
	"github.com/mattn/go-isatty"
)

// errNoTerminal is returned by prompter.confirm when there is nobody to
// ask: stdin is a pipe, a file, or a CI runner's null device.
//
// It is an error rather than "just use the default" on purpose. A default
// is a guess about what someone would have said, and for a question about
// publishing their email address, guessing is precisely the thing to avoid.
// Callers translate it into the safe outcome for their situation — leaving
// a field blank, or refusing to push.
var errNoTerminal = errors.New("no terminal to ask on")

// prompter reads yes/no answers from a person. The streams are fields
// rather than package globals so the confirmation logic can be tested
// without a terminal, which is the only way to test the case that matters:
// what happens when there isn't one.
type prompter struct {
	in          io.Reader
	out         io.Writer
	interactive bool
}

// newPrompter wires a prompter to the real terminal. interactive is false
// whenever stdin isn't a terminal, which is what makes an unattended run
// take the private-by-default path instead of blocking forever on a read
// that will never return.
func newPrompter() *prompter {
	return &prompter{
		in:          os.Stdin,
		out:         os.Stdout,
		interactive: isatty.IsTerminal(os.Stdin.Fd()) || isatty.IsCygwinTerminal(os.Stdin.Fd()),
	}
}

// confirm asks question and reads a yes/no answer. def is what a bare
// Enter means.
//
// Only an explicit yes/y (or an empty line when def is true) counts as
// agreement — an unrecognized answer is a no, because the cost of
// misreading "maybe" as consent is higher than the cost of asking again.
// EOF is a no for the same reason, whatever def says.
func (p *prompter) confirm(question string, def bool) (bool, error) {
	if !p.interactive {
		return false, errNoTerminal
	}

	hint := "[y/N]"
	if def {
		hint = "[Y/n]"
	}
	fmt.Fprintf(p.out, "%s %s ", question, hint)

	line, err := bufio.NewReader(p.in).ReadString('\n')
	if err != nil && line == "" {
		// Includes io.EOF: stdin closed mid-question. Not consent.
		return false, nil
	}

	switch strings.ToLower(strings.TrimSpace(line)) {
	case "y", "yes":
		return true, nil
	case "":
		return def, nil
	default:
		return false, nil
	}
}

// resolveManifestAuthor decides what to pre-fill omarket.json's author
// field with, and returns a note to print explaining the decision.
//
// The author field ends up in a public catalog. git config will almost
// always offer *something* — and its universal fallback, user.email, is a
// personal address its owner never agreed to publish. Silently writing that
// into the template is a leak waiting for the first seller who doesn't read
// the file before pushing.
//
// So the value is still looked up, because it usually is the right answer
// and typing it again is a chore, but what happens next depends on what it
// is: a GitHub handle is used outright (it is already public, and prompting
// about it would only teach people to hit y without reading), while an
// email address is shown in full and used only if the person says yes.
// Declining, or having no terminal to be asked on, leaves the field empty —
// client.ManifestIssues then requires it before anything can be pushed, so
// the failure mode is a small chore rather than a disclosure.
func resolveManifestAuthor(p *prompter, candidate client.AuthorCandidate) (author, note string) {
	if !candidate.Found() {
		return "", ""
	}
	if !candidate.Private() {
		return candidate.Value, "Pre-filled author from git config (" + string(candidate.Source) + "): " + candidate.Value
	}

	ok, err := p.confirm(
		"git config has your email address ("+candidate.Value+").\n"+
			"  Use it as the public author of this listing? It will appear in the catalog.", false)
	if err != nil || !ok {
		return "", `Left "author" blank — your git email is not published without your say-so. Fill it in before pushing.`
	}
	return candidate.Value, "Using " + candidate.Value + " as the public author, as confirmed."
}

// confirmPublishAuthor is the second gate, at push time: whatever is in the
// manifest's author field is about to be published, and if it is an email
// address the person gets one last chance to say no.
//
// It exists in addition to the claim-time prompt because the two catch
// different things. That one covers the value the CLI itself suggested;
// this one covers a manifest written by hand, copied from another project,
// generated by an older version of this CLI, or edited since — none of
// which went past a prompt.
//
// assumeYes (the -yes flag) is how a script says the address is meant to be
// public. Without it, an unattended push of an email-shaped author fails
// rather than proceeding, because a CI job cannot consent on someone's
// behalf.
func confirmPublishAuthor(p *prompter, author string, assumeYes bool) error {
	if assumeYes || !client.LooksLikeEmail(author) {
		return nil
	}

	ok, err := p.confirm(
		"The author field is an email address ("+strings.TrimSpace(author)+").\n"+
			"  Pushing publishes it in the public catalog. Continue?", false)
	if errors.Is(err, errNoTerminal) {
		return fmt.Errorf("refusing to publish the email address %q without confirmation: "+
			"edit %s to use a handle instead, or pass -yes if you really do want it public",
			strings.TrimSpace(author), client.ManifestFilename)
	}
	if err != nil {
		return err
	}
	if !ok {
		return fmt.Errorf("cancelled: nothing was pushed — edit %s and use a handle instead", client.ManifestFilename)
	}
	return nil
}
